import { IFeaturedEvent } from "../types/constType";

export const featuredEvents: IFeaturedEvent[] = [
  {
    id: 1,
    title: "DeFi Bootcamp",
    description: "Intensive DeFi basics and hands-on yield farming strategies.",
    startDate: "2024-09-10",
    endDate: "2024-09-12",
    location: "Online",
    participant: 87,
    maxParticipant: 120,
    eventPrice: 120,
    commitmentPrice: 30,
    organizerName: "CryptoVerse",
    linkImg: "/assets/events/defi-bootcamp.jpg",
    StatusTags: "ON_SALE",
    organizer: "CryptoVerse",
    participants: [],
  },
  {
    id: 2,
    title: "Solidity for Beginners",
    description: "Get started with smart contract development using Solidity.",
    startDate: "2024-10-03",
    endDate: "2024-10-06",
    location: "Jakarta",
    participant: 48,
    maxParticipant: 70,
    eventPrice: 250,
    commitmentPrice: 80,
    organizerName: "DevChain Academy",
    linkImg: "/assets/events/solidity-beginner.jpg",
    StatusTags: "ON_SALE",
    organizer: "DevChain Academy",
    participants: [],
  },
  {
    id: 3,
    title: "NFT Creator Day",
    description: "Concept, mint and market your own NFTs in one day!",
    startDate: "2024-08-21",
    endDate: "2024-08-21",
    location: "Bandung",
    participant: 47,
    maxParticipant: 55,
    eventPrice: 75,
    commitmentPrice: 18,
    organizerName: "NFT Workshop",
    linkImg: "/assets/events/nft-creator.jpg",
    StatusTags: "ON_GOING",
    organizer: "NFT Workshop",
    participants: [],
  },
  {
    id: 4,
    title: "Metaverse Design Jam",
    description: "Collab and build mini-worlds using Unity & blockchain.",
    startDate: "2024-09-21",
    endDate: "2024-09-24",
    location: "Bali",
    participant: 40,
    maxParticipant: 60,
    eventPrice: 399,
    commitmentPrice: 100,
    organizerName: "MetaWorld Team",
    linkImg: "/assets/events/metaverse-jam.jpg",
    StatusTags: "ON_SALE",
    organizer: "MetaWorld Team",
    participants: [],
  },
  {
    id: 5,
    title: "Blockchain Essentials",
    description: "4 days to crypto, blockchain, and Web3 awareness.",
    startDate: "2024-08-10",
    endDate: "2024-08-13",
    location: "Online",
    participant: 112,
    maxParticipant: 180,
    eventPrice: 99,
    commitmentPrice: 30,
    organizerName: "BlockLab",
    linkImg: "/assets/events/blockchain-essentials.jpg",
    StatusTags: "ON_GOING",
    organizer: "BlockLab",
    participants: [],
  },
  {
    id: 6,
    title: "Crypto Trading Bootcamp",
    description: "Crash course in technical analysis, crypto markets & risk.",
    startDate: "2024-11-12",
    endDate: "2024-11-16",
    location: "Surabaya",
    participant: 65,
    maxParticipant: 100,
    eventPrice: 160,
    commitmentPrice: 50,
    organizerName: "TraderHub",
    linkImg: "/assets/events/trading-bootcamp.jpg",
    StatusTags: "ON_SALE",
    organizer: "TraderHub",
    participants: [],
  },
  {
    id: 7,
    title: "AI x Blockchain Summit",
    description: "The future intersection of AI and decentralized tech.",
    startDate: "2024-12-01",
    endDate: "2024-12-03",
    location: "Online",
    participant: 220,
    maxParticipant: 250,
    eventPrice: 400,
    commitmentPrice: 150,
    organizerName: "FutureWorks",
    linkImg: "/assets/events/ai-blockchain.jpg",
    StatusTags: "ON_SALE",
    organizer: "FutureWorks",
    participants: [],
  },
  {
    id: 8,
    title: "Web3 Startup Hackathon",
    description: "Turn your Web3 idea into MVP in 48 hours, pitch to VCs!",
    startDate: "2024-09-28",
    endDate: "2024-09-30",
    location: "Yogyakarta",
    participant: 70,
    maxParticipant: 80,
    eventPrice: 250,
    commitmentPrice: 90,
    organizerName: "BuildUp",
    linkImg: "/assets/events/web3-hackathon.jpg",
    StatusTags: "ON_GOING",
    organizer: "BuildUp",
    participants: [],
  },
  {
    id: 9,
    title: "Yield Farming Crash Course",
    description: "Make your crypto work for you, safely and profitably.",
    startDate: "2024-10-12",
    endDate: "2024-10-13",
    location: "Online",
    participant: 95,
    maxParticipant: 110,
    eventPrice: 55,
    commitmentPrice: 20,
    organizerName: "YieldMax",
    linkImg: "/assets/events/yield-farming.jpg",
    StatusTags: "ON_SALE",
    organizer: "YieldMax",
    participants: [],
  },
  {
    id: 10,
    title: "Digital Marketing for Crypto",
    description: "Master influencer, SEO & paid ads for blockchain projects.",
    startDate: "2024-12-05",
    endDate: "2024-12-10",
    location: "Online",
    participant: 41,
    maxParticipant: 60,
    eventPrice: 180,
    commitmentPrice: 60,
    organizerName: "GrowthAlliance",
    linkImg: "/assets/events/digital-marketing.jpg",
    StatusTags: "FINISHED",
    organizer: "GrowthAlliance",
    participants: [],
  },
];
